{% set name = "sortedcontainers-stubs" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sortedcontainers_stubs-{{ version }}.tar.gz
  sha256: ba172daceda4bd617d2f6ffd24582261a494da92705409651967faa40ebc75dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - sortedcontainers >=2.0.0,<3.0.0
    - typing_extensions >=4.1.0,<5.0.0

test:
  imports:
    - sortedcontainers
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/h4l/sortedcontainers-stubs
  summary: Type stubs for sortedcontainers
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - h4l
